Altering Data

In [38]:
import pandas as pd

In [39]:
people = {
    "first":["Shreyansh",'Jane','John'],
    "last":["Kumar",'Doe','Doe'],
    "email":["shre@gmail.com",'JaneDoe@gmail.com','JohnDoe@gmail.com']
}

In [40]:
df = pd.DataFrame(people)

In [41]:
df

       first   last              email
0  Shreyansh  Kumar     shre@gmail.com
1       Jane    Doe  JaneDoe@gmail.com
2       John    Doe  JohnDoe@gmail.com

In [42]:
df.columns

Index(['first', 'last', 'email'], dtype='str')

In [43]:
# changing column name(M1)
df.columns = ['first_name', 'last_name', 'email']

In [44]:
df.columns

Index(['first_name', 'last_name', 'email'], dtype='str')

In [45]:
df

  first_name last_name              email
0  Shreyansh     Kumar     shre@gmail.com
1       Jane       Doe  JaneDoe@gmail.com
2       John       Doe  JohnDoe@gmail.com

In [46]:
# uppercase to lowercase and vice versa
# colmnn name have spaces and want to replace them
# in the above two cases we use list comprehension

In [47]:
# for example: I want to get all of the columns to be uppercase
df.columns = [x.lower() for x in df.columns]
df

  first_name last_name              email
0  Shreyansh     Kumar     shre@gmail.com
1       Jane       Doe  JaneDoe@gmail.com
2       John       Doe  JohnDoe@gmail.com

In [48]:
# For Example 2: Replace spaces with underscores
df.columns = df.columns.str.replace(' ', '_')
df

  first_name last_name              email
0  Shreyansh     Kumar     shre@gmail.com
1       Jane       Doe  JaneDoe@gmail.com
2       John       Doe  JohnDoe@gmail.com

In [49]:
# Example 3: We want to change some column (rename method and we will pass a dictionary)
df.rename(columns={
    'first_name':'first',
    'last_name': 'last'
},inplace=True)
df

       first   last              email
0  Shreyansh  Kumar     shre@gmail.com
1       Jane    Doe  JaneDoe@gmail.com
2       John    Doe  JohnDoe@gmail.com

In [50]:
# Example 4: Updating data in rows
# Single value
df.loc[2] = ['John','Smith','JohnSmith@email.com']
df

       first   last                email
0  Shreyansh  Kumar       shre@gmail.com
1       Jane    Doe    JaneDoe@gmail.com
2       John  Smith  JohnSmith@email.com

In [51]:
# Multiple value
df.loc[2, ['last', 'email']] = ['Doe', 'JohnDoe@email.com']
df

       first   last              email
0  Shreyansh  Kumar     shre@gmail.com
1       Jane    Doe  JaneDoe@gmail.com
2       John    Doe  JohnDoe@email.com

In [52]:
# Example 5: To change only one value
df.loc[2, 'last'] = 'Smith'
df

       first   last              email
0  Shreyansh  Kumar     shre@gmail.com
1       Jane    Doe  JaneDoe@gmail.com
2       John  Smith  JohnDoe@email.com

In [53]:
# another way 
df.at[2, 'last'] = 'Doe'
df

       first   last              email
0  Shreyansh  Kumar     shre@gmail.com
1       Jane    Doe  JaneDoe@gmail.com
2       John    Doe  JohnDoe@email.com

In [54]:
# Common Mistake
filt=(df['email'] == 'JohnDoe@email.com')
df[filt]['last']='Smith'
df

C:\Users\Shreyansh kumar\AppData\Local\Temp\ipykernel_6244\3230418051.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  df[filt]['last']='Smith'

       first   last              email
0  Shreyansh  Kumar     shre@gmail.com
1       Jane    Doe  JaneDoe@gmail.com
2       John    Doe  JohnDoe@email.com

In [55]:
filt=(df['email'] == 'JohnDoe@email.com')
df.loc[filt, 'last']='Smith'
df

       first   last              email
0  Shreyansh  Kumar     shre@gmail.com
1       Jane    Doe  JaneDoe@gmail.com
2       John  Smith  JohnDoe@email.com

In [56]:
# Example 6: Email Address to lowercase
df['email'] = df['email'].str.lower()
df

       first   last              email
0  Shreyansh  Kumar     shre@gmail.com
1       Jane    Doe  janedoe@gmail.com
2       John  Smith  johndoe@email.com

In [ ]:
# 4methods
#1. apply---->used for calling a function on our values(works on either dataframe or series object)
#2. map------> works only on series
#3. applymap---->only works on DataFrames
#4. replace

In [106]:
# working with series object
df['email'].apply(len)

0    14
1    17
2    17
Name: email, dtype: int64

In [107]:
def update_email(email):
    return email.upper()

df['email'].apply(update_email) # changes from lowercase to uppercase
#-----------------------------------------------------------------------
# Prints the table
df['email'] = df['email'].apply(update_email)
df

       first   last              email
0  Shreyansh  Kumar     SHRE@GMAIL.COM
1       Jane    Doe  JANEDOE@GMAIL.COM
2       John  Smith  JOHNDOE@EMAIL.COM

In [108]:
# Using lambda functions
df['email'] = df['email'].apply(lambda x: x.lower())
df

       first   last              email
0  Shreyansh  Kumar     shre@gmail.com
1       Jane    Doe  janedoe@gmail.com
2       John  Smith  johndoe@email.com

In [109]:
# with rows and columns(dataframes) 
df['email'].apply(len)

0    14
1    17
2    17
Name: email, dtype: int64

In [110]:
# applying length functions to each series in the dataframe specifically the columns
df.apply(len, axis = 'columns')

0    3
1    3
2    3
dtype: int64

In [111]:
# accessing one of these columns
len(df['email'])

3

In [112]:
#Example : Grabbing the minimum value from each column
df.apply(pd.Series.min)

first                 Jane
last                   Doe
email    janedoe@gmail.com
dtype: str

# Note: Lambda function working with series object

In [113]:
df.apply(lambda x: x.min())

first                 Jane
last                   Doe
email    janedoe@gmail.com
dtype: str

In [114]:
df.map(len)

   first  last  email
0      9     5     14
1      4     3     17
2      4     5     17

In [115]:
# all the value in the dataframe are coverted to lowercase
df.map(str.lower)

       first   last              email
0  shreyansh  kumar     shre@gmail.com
1       jane    doe  janedoe@gmail.com
2       john  smith  johndoe@email.com

In [130]:
df['first'] =df['first'].replace(
    {
        'Shreyansh':'Chris',
        'Jane':'Mary'
    }
)
df

   first   last              email  firsy
0  Chris  Kumar     shre@gmail.com  Chris
1   Mary    Doe  janedoe@gmail.com   Mary
2   John  Smith  johndoe@email.com   John