In [2]:
# familiar with dictionaries where we have keys and values

person = {
    "first": "Shreyansh",
    "last" : "Kumar",
    "email": "shreyan.kumar29@gmail.com"
}

In [3]:
people = {
    "first": ["Shreyansh"],
    "last" : ["Kumar"],
    "email": ["shreyan.kumar29@gmail.com"]
}

In [8]:
# Thinking of
# Keys ------> Columns
# Values ------> Rows
people = {
    "first": ["Shreyansh", "Jane", "John"],
    "last": ["Kumar", "Doe", "Doe"],
    "email": [
        "shreyan.kumar29@gmail.com",
        "Jane@gmail.com",
        "JohnDoe@gmail.com"
    ]
}

In [5]:
# Accessing email
people['email']

['shreyan.kumar29@gmail.com', 'Jane@gmail.com', 'JohnDoe@gmail.com']

# Creating a DataFrame

In [3]:
people = {
    "first": ["Shreyansh", "Jane", "John"],
    "last": ["Kumar", "Doe", "Doe"],
    "email": [
        "shreyan.kumar29@gmail.com",
        "Jane@gmail.com",
        "JohnDoe@gmail.com"
    ]
}

In [6]:
import pandas as pd
df = pd.DataFrame(people)

In [7]:
df

       first   last                      email
0  Shreyansh  Kumar  shreyan.kumar29@gmail.com
1       Jane    Doe             Jane@gmail.com
2       John    Doe          JohnDoe@gmail.com

# Index--->Unique values for row

In [9]:
# Accessing emails from DataFrames
df['email']

0    shreyan.kumar29@gmail.com
1               Jane@gmail.com
2            JohnDoe@gmail.com
Name: email, dtype: str

In [10]:
# Checking the type of emaiL
type(df['email'])

pandas.Series

# Series---> list of data, just like DataFrame having lots of functionality

# DataFrame is a containner containing multiple series objects.

In [13]:
# other way of accessing email from dataframes
df.email

0    shreyan.kumar29@gmail.com
1               Jane@gmail.com
2            JohnDoe@gmail.com
Name: email, dtype: str

In [14]:
# Errors in using dot notation for accessing
# Suppose we are having a count column in our datasets and if we try to write df.count it wouldn't work

In [15]:
# Accessing multiple columns
df[['last', 'email']]

    last                      email
0  Kumar  shreyan.kumar29@gmail.com
1    Doe             Jane@gmail.com
2    Doe          JohnDoe@gmail.com

In [16]:
# accessing all the columns
df.columns

Index(['first', 'last', 'email'], dtype='str')

In [17]:
# In order to get Rows We use loc aand iloc
# iloc allows us to access rowsby integer location(integer Location)
# loc ------> we are searching for labels

In [18]:
df.iloc[0]

first                    Shreyansh
last                         Kumar
email    shreyan.kumar29@gmail.com
Name: 0, dtype: str

In [20]:
# Accesing first and secong row
df.iloc[[0, 1]]

       first   last                      email
0  Shreyansh  Kumar  shreyan.kumar29@gmail.com
1       Jane    Doe             Jane@gmail.com

In [21]:
# if we think iloc and loc as functions then we want rows as first argument and columns as the second argument.
df.iloc[[0, 1],2]

0    shreyan.kumar29@gmail.com
1               Jane@gmail.com
Name: email, dtype: str

In [22]:
df

       first   last                      email
0  Shreyansh  Kumar  shreyan.kumar29@gmail.com
1       Jane    Doe             Jane@gmail.com
2       John    Doe          JohnDoe@gmail.com

In [23]:
df.loc[0]

first                    Shreyansh
last                         Kumar
email    shreyan.kumar29@gmail.com
Name: 0, dtype: str

In [24]:
# Acccessing first and second row
df.loc[[0 ,1]]

       first   last                      email
0  Shreyansh  Kumar  shreyan.kumar29@gmail.com
1       Jane    Doe             Jane@gmail.com

In [25]:
# Accessing first and last row wwith email
df.loc[[0 ,1],'email']

0    shreyan.kumar29@gmail.com
1               Jane@gmail.com
Name: email, dtype: str

In [26]:
#last name and email
df.loc[[0 ,1],['email','last']]

                       email   last
0  shreyan.kumar29@gmail.com  Kumar
1             Jane@gmail.com    Doe