In [8]:
import pandas as pd
import numpy as np

In [9]:
people = {
    'first': ['Corey', 'Jane', 'John', 'Chris', np.nan, None, 'NA'], 
    'last': ['Schafer', 'Doe', 'Doe', 'Schafer', np.nan, np.nan, 'Missing'], 
    'email': ['CoreyMSchafer@gmail.com', 'JaneDoe@email.com', 'JohnDoe@email.com', None, np.nan, 'Anonymous@email.com', 'NA'],
    'age': ['33', '55', '63', '36', None, None, 'Missing']
}

# nan stands for not a number value

In [10]:
df = pd.DataFrame(people)

In [11]:
df

   first     last                    email      age
0  Corey  Schafer  CoreyMSchafer@gmail.com       33
1   Jane      Doe        JaneDoe@email.com       55
2   John      Doe        JohnDoe@email.com       63
3  Chris  Schafer                      NaN       36
4    NaN      NaN                      NaN      NaN
5    NaN      NaN      Anonymous@email.com      NaN
6     NA  Missing                       NA  Missing

# Dropping Missing Values

In [14]:
# Example: Removing the rows that have none values
# M1:
df.dropna()

   first     last                    email      age
0  Corey  Schafer  CoreyMSchafer@gmail.com       33
1   Jane      Doe        JaneDoe@email.com       55
2   John      Doe        JohnDoe@email.com       63
6     NA  Missing                       NA  Missing

In [20]:
# M2:
df.dropna(axis='index', how='any')

# Explaination:
# 1. axis argument--->
#    a.)either set to index or set to column
#    b.)
#      I.)when set to index------>tell pandas that we want to drop na values when our rows are having missing values
#      II.)when set to columns--->if will drop the columns that have missing values
# 2. how argument---->
#    a.)how we want to drop these values
#    b.)uses for dropping a row or a column
#    c.)by default how='any'
#  3.df.dropna(axis='index', how='any')-----> 
#  here axis is set to index and how is set any it means that it will drop rows with any missing values

   first     last                    email      age
0  Corey  Schafer  CoreyMSchafer@gmail.com       33
1   Jane      Doe        JaneDoe@email.com       55
2   John      Doe        JohnDoe@email.com       63
6     NA  Missing                       NA  Missing

In [22]:
# Example: Doesn't have an entire row that has missing values
df.dropna(axis='index', how='all')

# Explaination:
# df.dropna(axis='index', how='all')--> this will only drop rows when all of the values in that row are missing.

   first     last                    email      age
0  Corey  Schafer  CoreyMSchafer@gmail.com       33
1   Jane      Doe        JaneDoe@email.com       55
2   John      Doe        JohnDoe@email.com       63
3  Chris  Schafer                      NaN       36
5    NaN      NaN      Anonymous@email.com      NaN
6     NA  Missing                       NA  Missing

In [ ]:
# Example: