In [102]:
import pandas as pd
import numpy as np

In [103]:
people = {
    'first': ['Corey', 'Jane', 'John', 'Chris', np.nan, None, 'NA'], 
    'last': ['Schafer', 'Doe', 'Doe', 'Schafer', np.nan, np.nan, 'Missing'], 
    'email': ['CoreyMSchafer@gmail.com', 'JaneDoe@email.com', 'JohnDoe@email.com', None, np.nan, 'Anonymous@email.com', 'NA'],
    'age': ['33', '55', '63', '36', None, None, 'Missing']
}
# nan stands for not a number value

In [104]:
df = pd.DataFrame(people)

df.replace('NA', np.nan, inplace = True)
df.replace('Missing', np.nan, inplace = True)

   first     last                    email  age
0  Corey  Schafer  CoreyMSchafer@gmail.com   33
1   Jane      Doe        JaneDoe@email.com   55
2   John      Doe        JohnDoe@email.com   63
3  Chris  Schafer                      NaN   36
4    NaN      NaN                      NaN  NaN
5    NaN      NaN      Anonymous@email.com  NaN
6    NaN      NaN                      NaN  NaN

In [105]:
df

   first     last                    email  age
0  Corey  Schafer  CoreyMSchafer@gmail.com   33
1   Jane      Doe        JaneDoe@email.com   55
2   John      Doe        JohnDoe@email.com   63
3  Chris  Schafer                      NaN   36
4    NaN      NaN                      NaN  NaN
5    NaN      NaN      Anonymous@email.com  NaN
6    NaN      NaN                      NaN  NaN

# Dropping Missing Values

In [106]:
# Example: Removing the rows that have none values
# M1:
df.dropna()

   first     last                    email age
0  Corey  Schafer  CoreyMSchafer@gmail.com  33
1   Jane      Doe        JaneDoe@email.com  55
2   John      Doe        JohnDoe@email.com  63

In [107]:
# M2:
df.dropna(axis='index', how='any')

# Explaination:
# 1. axis argument--->
#    a.)either set to index or set to column
#    b.)
#      I.)when set to index------>tell pandas that we want to drop na values when our rows are having missing values
#      II.)when set to columns--->if will drop the columns that have missing values
# 2. how argument---->
#    a.)how we want to drop these values
#    b.)uses for dropping a row or a column
#    c.)by default how='any'
#  3.df.dropna(axis='index', how='any')-----> 
#  here axis is set to index and how is set any it means that it will drop rows with any missing values

   first     last                    email age
0  Corey  Schafer  CoreyMSchafer@gmail.com  33
1   Jane      Doe        JaneDoe@email.com  55
2   John      Doe        JohnDoe@email.com  63

In [108]:
# Example: Doesn't have an entire row that has missing values
df.dropna(axis='index', how='all')

# Explaination:
# df.dropna(axis='index', how='all')--> this will only drop rows when all of the values in that row are missing.

   first     last                    email  age
0  Corey  Schafer  CoreyMSchafer@gmail.com   33
1   Jane      Doe        JaneDoe@email.com   55
2   John      Doe        JohnDoe@email.com   63
3  Chris  Schafer                      NaN   36
5    NaN      NaN      Anonymous@email.com  NaN

# Dropping subset of data

In [109]:
# Example: Changing axis = 'index' to axis='columns'
df.dropna(axis='columns', how='all')

   first     last                    email  age
0  Corey  Schafer  CoreyMSchafer@gmail.com   33
1   Jane      Doe        JaneDoe@email.com   55
2   John      Doe        JohnDoe@email.com   63
3  Chris  Schafer                      NaN   36
4    NaN      NaN                      NaN  NaN
5    NaN      NaN      Anonymous@email.com  NaN
6    NaN      NaN                      NaN  NaN

In [110]:
df.dropna(axis='columns', how='any')
# an empty index

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6]

# Adavnced Dropping Techniques

In [111]:
# Example: Suppose if thee dataframe doesn't contain first name and the last name and we need the email address and if they don't have an email address then we need to just drop those rows.
df.dropna(axis='index', how='any', subset=['email'])

# df.dropna(axis='index', how='all', subset=['email'])------------->gives the same result

   first     last                    email  age
0  Corey  Schafer  CoreyMSchafer@gmail.com   33
1   Jane      Doe        JaneDoe@email.com   55
2   John      Doe        JohnDoe@email.com   63
5    NaN      NaN      Anonymous@email.com  NaN

In [112]:
# Example: in order for my data to be useful I need either their last name or their email address but I don't need both
df.dropna(axis='index', how='all', subset=['last', 'email'])
# Explaination:
# In this case the person is having the last name but not the email and vice versa because we have passed how='all' which means row to be dropped both the subset columns to be missing.

   first     last                    email  age
0  Corey  Schafer  CoreyMSchafer@gmail.com   33
1   Jane      Doe        JaneDoe@email.com   55
2   John      Doe        JohnDoe@email.com   63
3  Chris  Schafer                      NaN   36
5    NaN      NaN      Anonymous@email.com  NaN

# Filling Missing Values

In [113]:
df.isna()

   first   last  email    age
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False   True  False
4   True   True   True   True
5   True   True  False   True
6   True   True   True   True

In [114]:
df.fillna('MISSING')

     first     last                    email      age
0    Corey  Schafer  CoreyMSchafer@gmail.com       33
1     Jane      Doe        JaneDoe@email.com       55
2     John      Doe        JohnDoe@email.com       63
3    Chris  Schafer                  MISSING       36
4  MISSING  MISSING                  MISSING  MISSING
5  MISSING  MISSING      Anonymous@email.com  MISSING
6  MISSING  MISSING                  MISSING  MISSING

In [115]:
df.fillna(0)

   first     last                    email age
0  Corey  Schafer  CoreyMSchafer@gmail.com  33
1   Jane      Doe        JaneDoe@email.com  55
2   John      Doe        JohnDoe@email.com  63
3  Chris  Schafer                        0  36
4      0        0                        0   0
5      0        0      Anonymous@email.com   0
6      0        0                        0   0

# Casting Data Types

In [116]:
# Example: Average age of all the people in the sample dataframe
df.dtypes

first    str
last     str
email    str
age      str
dtype: object

In [117]:
df['age'].mean()

TypeError: Cannot perform reduction 'mean' with string dtype

In [118]:
# When converting from NaN values in Numbers then we use float datatypes

In [119]:
type(np.nan)

float

In [122]:
# Coverting datatype
df['age'] = df['age'].astype(int)

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer.Replace or remove non-finite values or cast to an integer typethat supports these values (e.g. 'Int64')

# Converting types with NaN

In [123]:
df['age'] = df['age'].astype(float)

In [124]:
df.dtypes

first        str
last         str
email        str
age      float64
dtype: object

In [126]:
df['age'].mean()

np.float64(46.75)

In [127]:
# Note: Now if we have an entire dataframe of numbers or something like that we are trying to convert all at once then the datatype object has an astype method as well